services:
  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

  frontend:
    build:
      context: ./FE
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - backend
  mongo:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
