name: Deploy to EC2

on:
  push:
    branches:
      - main # or master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy FE + BE
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/app || git clone https://github.com/omelandah/nextblog.git ~/app
            cd ~/app
            git pull origin main

            # Install deps
            cd fe && npm install && cd ..
            cd be && npm install && cd ..

            # Restart via ecosystem
            pm2 reload ecosystem.config.js --update-env
            pm2 save
